import autodisc.cppn.activations
import autodisc.cppn.helper
import autodisc.cppn.neatcppngui
import autodisc.cppn.pytorchcppn
import autodisc.cppn.selfconnectiongenome
import autodisc.cppn.twodmatrixcppnneatevolution

from autodisc.cppn.selfconnectiongenome import SelfConnectionGenome
from autodisc.cppn.twodmatrixcppnneatevolution import TwoDMatrixCCPNNEATEvolution
