from autodisc.representations.static.statisticsrepresentation import StatisticRepresentation
from autodisc.representations.static.pytorchnnrepresentation.pytorchnnrepresentation import PytorchNNRepresentation
import autodisc.representations.static.pytorchnnrepresentation


